<?php

namespace AppBundle\Repository;

/**
 * MarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarcaRepository extends \Doctrine\ORM\EntityRepository {

    //QueryBuilders used in the generation of Form's drop down lists
    function getMarcasQueryBuilder() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select('e')
                        ->from('AppBundle:Marca','e');

    }

}
