<?php

namespace AppBundle\Repository;

/**
 * ProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoRepository extends \Doctrine\ORM\EntityRepository {

    public function findAllActive() {
        return $this->getEntityManager()
                        ->createQuery(
                                "SELECT o FROM AppBundle:Producto o  ORDER BY o.id DESC"
                        )
                        ->getResult();
    }

}
