<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
        function getUserQueryBuilder() {
        $qb = $this->getEntityManager()->createQueryBuilder();
        return $qb->select('e')
                        ->from('AppBundle:User','e');

    }
}
